Repository TeamCooks/TwoSpoon, pull requests merged in 2022-03, with the labels that each got.

#2 conf: 프로젝트를 위한 초기 환경 구성 - Issue #1
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  .storybook/main.js
  .storybook/preview.js
  package.json
  public/assets/favicon.ico
  public/assets/logo192.png
  public/assets/logo512.png
  public/index.html
  public/manifest.json
  public/robots.txt
  src/assets/logo.svg
  src/components/App/App.css
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/index.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/stories/README.md
  src/stories/example/assets/code-brackets.svg
  src/stories/example/assets/colors.svg
  src/stories/example/assets/comments.svg
  src/stories/example/assets/direction.svg
  src/stories/example/assets/flow.svg
  src/stories/example/assets/plugin.svg
  src/stories/example/assets/repo.svg
  src/stories/example/assets/stackalt.svg
  src/stories/example/button/button.css
  src/stories/example/button/button.jsx
  src/stories/example/button/button.stories.jsx
  src/stories/example/header/header.css
  src/stories/example/header/header.jsx
  src/stories/example/header/header.stories.jsx
  src/stories/example/introduction.stories.mdx
  src/stories/example/page/page.css
  src/stories/example/page/page.jsx
  src/stories/example/page/page.stories.jsx
  src/styles/global.css
  src/utils/.keep
  tsconfig.json
  yarn.lock
Labels: ⚙️ conf

#3 초기 환경구성
  .github/PULL_REQUEST_TEMPLATE.md
  src/api/.keep
  src/hooks/.keep
  src/pages/.keep
Labels: ⚙️ conf

#6 Develop
  README.md
  package.json
Labels: 📝 documentation, ⚙️ conf

#7 docs: Update README.md
  README.md
Labels: 📝 documentation

#20 feat: 전역 스타일링 설정 및 스타일 관련 util함수 추가와 Label 컴포넌트 마이그레이션
  package.json
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.styled.tsx
  src/components/Label/Label.tsx
  src/components/Label/Label.types.ts
  src/components/index.ts
  src/index.tsx
  src/styles/GlobalStyle.ts
  src/styles/fonts/Montserrat-Bold.woff2
  src/styles/fonts/Montserrat-Regular.woff2
  src/styles/global.css
  src/theme/theme.d.ts
  src/theme/theme.ts
  src/utils/.keep
  src/utils/index.ts
  src/utils/style.ts
  yarn.lock
Labels: 🌟 feature, ✨ style, ⚙️ conf

#23 conf: feature 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ⚙️ conf

#39 라우팅 초기작업
  .github/ISSUE_TEMPLATE/feature_request.md
  package.json
  src/components/App/App.tsx
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.styled.tsx
  src/components/Label/Label.tsx
  src/components/Label/Label.types.ts
  src/components/index.ts
  src/index.tsx
  src/pages/Home/Home.tsx
  src/pages/Layout/Layout.tsx
  src/pages/Modal/Modal.tsx
  src/pages/MyRecipes/MyRecipes.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/pages/Search/Search.tsx
  src/styles/GlobalStyle.ts
  src/styles/fonts/Montserrat-Bold.woff2
  src/styles/fonts/Montserrat-Regular.woff2
  src/styles/global.css
  src/theme/theme.d.ts
  src/theme/theme.ts
  src/utils/.keep
  src/utils/index.ts
  src/utils/style.ts
  yarn.lock
Labels: 🌟 feature, ✈️ migration

#32 Label 컴포넌트 리팩토링 -> CookingInfo 컴포넌트로 변경
  README.md
  public/index.html
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/CookingInfo/CookingInfo.stories.tsx
  src/components/CookingInfo/CookingInfo.styled.tsx
  src/components/CookingInfo/CookingInfo.tsx
  src/components/CookingInfo/CookingInfo.types.ts
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.styled.tsx
  src/components/Label/Label.tsx
  src/components/Label/Label.types.ts
  src/components/index.ts
Labels: 🛠 refactor

#40 라우팅 초기작업
  package.json
  src/components/App/App.tsx
  src/index.tsx
  src/pages/Home/Home.tsx
  src/pages/Layout/Layout.tsx
  src/pages/Modal/Modal.tsx
  src/pages/MyRecipes/MyRecipes.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/pages/Search/Search.tsx
  yarn.lock
Labels: 🌟 feature, ✈️ migration

#44 conf: Storybook GlobalStyle, MemoryRouter 적용 - Issue #43
  .storybook/preview.js
Labels: ⚙️ conf

#42 Loading 컴포넌트 마이그레이션
  README.md
  public/index.html
  src/components/CookingInfo/CookingInfo.styled.tsx
  src/components/Loading/Loading.stories.tsx
  src/components/Loading/Loading.styled.tsx
  src/components/Loading/Loading.tsx
  src/components/Loading/Loading.types.ts
  src/components/index.ts
  src/styles/GlobalStyle.ts
  src/utils/dom.ts
  src/utils/index.ts
Labels: 🌟 feature, ✨ style, ✈️ migration, 🧱 component

#47 docs: 기술스택 변경 - Issue #46
  README.md
Labels: 📝 documentation

#49 CRA에서 Next.js로 환경 변경
  .babelrc
  .gitignore
  .storybook/main.js
  .storybook/preview-body.html
  .storybook/preview.js
  next-env.d.ts
  next.config.js
  package.json
  public/assets/favicon.ico
  public/assets/logo192.png
  public/assets/logo512.png
  public/favicon.ico
  public/fonts/Montserrat-Bold.woff2
  public/fonts/Montserrat-Regular.woff2
  public/index.html
  public/manifest.json
  public/robots.txt
  public/vercel.svg
  src/assets/logo.svg
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/CookingInfo/CookingInfo.styled.tsx
  src/components/Loading/Loading.styled.tsx
  src/components/Loading/Loading.tsx
  src/components/index.ts
  src/index.tsx
  src/pages/.keep
  src/pages/404.tsx
  src/pages/Home/Home.tsx
  src/pages/Layout/Layout.tsx
  src/pages/MyRecipes/MyRecipes.tsx
  src/pages/PageNotFound/PageNotFound.tsx
  src/pages/Search/Search.tsx
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/pages/modal.tsx
  src/pages/myRecipes.tsx
  src/pages/search.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/GlobalStyle.ts
  src/styles/GlobalStyle.tsx
  src/theme/theme.d.ts
  src/theme/theme.ts
  tsconfig.json
  yarn.lock
Labels: 🌟 feature, ⚙️ conf, ✈️ migration

#50 EmptyPage와 Layout, Pagination 컴포넌트 작업
  src/components/EmptyPage/EmptyPage.stories.tsx
  src/components/EmptyPage/EmptyPage.styled.tsx
  src/components/EmptyPage/EmptyPage.tsx
  src/components/EmptyPage/EmptyPage.types.ts
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Layout/Layout.stories.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/Layout.types.ts
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.styled.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/Pagination.types.ts
  src/components/index.ts
  src/pages/404.tsx
  src/pages/_app.tsx
Labels: 🌟 feature, ✨ style, ✈️ migration, 🧱 component

#54 로고, 버튼, 아이콘버튼 마이그레이션, ThemeProvider 스토리북에 적용
  .storybook/preview.js
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.styled.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/Button/IconButton.stories.tsx
  src/components/Button/IconButton.styled.tsx
  src/components/Button/IconButton.tsx
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.styled.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoIcon.tsx
  src/components/index.ts
  src/utils/style.ts
Labels: ✈️ migration, 🧱 component

#55 Auth 컴포넌트 작성, 필요 라이브러리 설치
  .gitignore
  package.json
  src/api/requestAuth.ts
  src/components/Auth/Auth.stories.tsx
  src/components/Auth/Auth.styled.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/Auth.types.ts
  src/components/Auth/AuthServices.ts
  src/components/EmptyPage/EmptyPage.stories.tsx
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.styled.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/Pagination.types.ts
  src/hooks/usePageNum.ts
  yarn.lock
Labels: 🌟 feature, ⚙️ conf, ✈️ migration, 🧱 component

#56 스켈레톤 컴포넌트 마이그레이션 및 rtk query 데모
  .eslintrc.js
  package.json
  src/api/.keep
  src/api/firebaseConfig.ts
  src/components/SkeletonCard/SkeletonCard.stories.tsx
  src/components/SkeletonCard/SkeletonCard.styled.tsx
  src/components/SkeletonCard/SkeletonCard.tsx
  src/components/SkeletonCard/SkeletonCard.types.ts
  src/components/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/store/index.tsx
  src/store/services/index.ts
  src/store/services/types/queries.ts
  src/store/slices/recipeReducer.ts
  src/utils/style.ts
  yarn.lock
Labels: 🌟 feature, ✈️ migration, 🧱 component

#58 conf: fireBaseConfig 레포에서 삭제
  src/api/firebaseConfig.ts
Labels: ⚙️ conf

#57 Badge 컴포넌트 마이그레이션 완료
  .storybook/main.js
  next.config.js
  package.json
  src/assets/icons/dairyFree.svg
  src/assets/icons/lactoOvo.svg
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.styled.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/Badge.types.ts
  yarn.lock
Labels: ⚙️ conf, 🧱 component

#59 Develop
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/Heading.styled.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/Heading.types.ts
  src/components/index.ts
Labels: 🌟 feature, ✈️ migration, 🧱 component

#60 SearchForm, Menu, Header컴포넌트 마이그레이션, 404일때 url 주소 변경
  package.json
  src/assets/icons/logo.svg
  src/components/Button/Button.types.ts
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/Logo/Logo.styled.tsx
  src/components/Logo/LogoIcon.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/Menu.styled.tsx
  src/components/Menu/Menu.tsx
  src/components/SearchForm/SearchForm.stories.tsx
  src/components/SearchForm/SearchForm.styled.tsx
  src/components/SearchForm/SearchForm.tsx
  src/components/index.ts
  src/pages/404.tsx
  yarn.lock
Labels: 🌟 feature, ✨ style, 🛠 refactor, ⚙️ conf, ✈️ migration, 🧱 component

#62 Search 페이지 서버사이드 렌더링 구현
  .storybook/preview-body.html
  package.json
  src/components/Auth/Auth.styled.tsx
  src/components/Auth/Auth.tsx
  src/components/Button/Button.styled.tsx
  src/components/Button/Button.types.ts
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/Dialog.styled.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/Dialog.types.ts
  src/pages/_document.tsx
  src/pages/search/[keyword].tsx
  src/utils/index.ts
  src/utils/tabbable.ts
Labels: 🌟 feature, ✈️ migration

#63 Auth와 Dialog 컴포넌트 + auth 관련하여 RTK 로직 추가, ErrorBoundary 컴포넌트 작성 및 Sentry 연동
  .gitignore
  .storybook/preview-body.html
  next.config.js
  next.config.wizardcopy.js
  package.json
  sentry.client.config.js
  sentry.properties
  sentry.server.config.js
  src/components/Auth/Auth.stories.tsx
  src/components/Auth/Auth.styled.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/Auth.types.ts
  src/components/Auth/AuthServices.ts
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/Dialog.styled.tsx
  src/components/EmptyPage/EmptyPage.styled.tsx
  src/components/ErrorBoundary/ErrorBoundary.stories.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundary.types.ts
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/components/Layout/Layout.styled.tsx
  src/components/Layout/Layout.tsx
  src/components/Menu/Menu.tsx
  src/components/Pagination/Pagination.styled.tsx
  src/components/index.ts
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/errorTest.tsx
  src/pages/search/[keyword].tsx
  src/pages/search/search.types.ts
  src/store/index.tsx
  src/store/slices/auth.ts
  yarn.lock
Labels: 🌟 feature, ✨ style, 🧪 test, 🧱 component

#65 Toast, BadgeList 컴포넌트 추가
  .storybook/preview-body.html
  src/components/Badge/Badge.types.ts
  src/components/BadgeList/BadgeList.styled.tsx
  src/components/BadgeList/BadgeList.types.ts
  src/components/Header/Header.styled.tsx
  src/components/Layout/Layout.styled.tsx
  src/components/Layout/Layout.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.styled.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/Toast.types.ts
  src/pages/_document.tsx
  src/styles/GlobalStyle.tsx
  src/utils/misc.ts
Labels: ✨ style, 🧱 component

#66 테마 타입 인식 오류 해결, Collapse 컴포넌트, Accordion 컴포넌트 마이그레이션
  src/components/Accordion/Accordion.stories.tsx
  src/components/Accordion/Accordion.styled.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accordion.types.ts
  src/components/Accordion/Collapse.tsx
  src/components/Accordion/CollapseContent.tsx
  src/components/Accordion/CollapseHeading.tsx
  src/components/index.ts
  src/theme/emotion.d.ts
Labels: ✨ style, 🛠 refactor, 💉 fix, ✈️ migration, 🧱 component

#64 Dialog와 Auth 버그 수정 및 스타일링 최종 완료
  src/components/Auth/Auth.styled.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/Auth.types.ts
  src/components/Dialog/Dialog.stories.tsx
  src/components/Dialog/Dialog.styled.tsx
  src/components/Dialog/Dialog.tsx
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundary.types.ts
  src/components/Header/Header.styled.tsx
  src/components/Header/Header.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/Menu.types.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useToast.ts
  src/pages/_error.tsx
  src/pages/errorTest.tsx
  src/store/slices/auth.ts
Labels: ✨ style, 🛠 refactor, 💉 fix

#69 Cardlist 컴포넌트 마이그레이션
  src/components/Accordion/Accordion.styled.tsx
  src/components/Card/Card.tsx
  src/components/CardList/CardList.stories.tsx
  src/components/CardList/CardList.styled.tsx
  src/components/CardList/CardList.tsx
  src/components/CardList/CardList.types.ts
  src/components/index.ts
Labels: 🌟 feature, ✈️ migration, 🧱 component

#71 코드 리팩토링및 RTK Query 수정
  .eslintrc.js
  package.json
  src/api/requestData.ts
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/CookingInfo/CookingInfo.styled.tsx
  src/components/HotRecipes/HotRecipes.styled.tsx
  src/components/HotRecipes/HotRecipes.tsx
  src/components/Loading/Loading.tsx
  src/components/RandomRecipe/RandomRecipe.styled.tsx
  src/components/RandomRecipe/RandomRecipe.tsx
  src/hooks/useRandomRecipe.ts
  src/store/slices/recipeReducer.ts
  src/stories/example/button/button.css
  src/stories/example/button/button.jsx
  src/stories/example/button/button.stories.jsx
  src/stories/example/header/header.css
  src/stories/example/header/header.jsx
  src/stories/example/header/header.stories.jsx
  src/stories/example/page/page.css
  src/stories/example/page/page.jsx
  src/stories/example/page/page.stories.jsx
  yarn.lock
Labels: 🛠 refactor, 💉 fix

#72 디테일 컴포넌트 완성, 레시피 디테일 페이지 서버사이드 렌더링
  src/api/customApi.ts
  src/components/Accordion/Accordion.styled.tsx
  src/components/Badge/Badge.tsx
  src/components/BadgeList/BadgeList.stories.tsx
  src/components/BadgeList/BadgeList.tsx
  src/components/CookingInfo/CookingInfo.styled.tsx
  src/components/Detail/Detail.stories.tsx
  src/components/Detail/Detail.styled.tsx
  src/components/Detail/Detail.tsx
  src/components/Detail/Detail.types.ts
  src/components/Header/Header.tsx
  src/components/Toast/Toast.styled.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useDialog.ts
  src/pages/index.tsx
  src/pages/recipe/[id].tsx
  src/theme/emotion.d.ts
  src/theme/theme.ts
  src/utils/misc.ts
Labels: ✨ style, ✈️ migration, 🧱 component

#73 로고에 커서 추가
  src/components/Logo/Logo.styled.tsx
Labels: ✨ style

#74 메인페이지 컴포넌트 조립 완료
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/HotRecipes/HotRecipes.styled.tsx
  src/components/HotRecipes/HotRecipes.tsx
  src/hooks/useHotRecipes.ts
  src/pages/index.tsx
Labels: 🌟 feature, 💉 fix

#75 feat: Meta 컴포넌트 생성
  src/components/Meta/Meta.tsx
  src/components/index.ts
  src/pages/index.tsx
Labels: 🌟 feature, ✈️ migration, 🧱 component

#77 Meta 버그 수정, Card 스타일 수정
  src/components/Card/Card.styled.tsx
  src/components/Card/Card.tsx
  src/components/Meta/Meta.tsx
  src/pages/index.tsx
Labels: 🐞 bug, 💉 fix
